### ISSUE TITLE
deleting one green rod deleted them all

### ISSUE THREAD

**Issue by bajohnso-uci** [whuang37/biondi_body_client#21]
I had previously tried multiple times to save the same green rod. The bug of failing to save it was fixed. When I went to image viewer, there were green rods 1-5, all the same image. I decided to delete all but one. I selected green rod 2 to delete. Once I did that, there were 4 "green rod 4"s. I deleted one of those, and they all disappeared.

**Comment by whuang37** [comment]
Fixed. Green rod left out of list to renumber bodies in SQL database
