### ISSUE TITLE
Unknown and Non-Biondi Body Markings Request

### ISSUE THREAD

**Issue by toddsoo** [whuang37/biondi_body_client#25]
I think it would be helpful to be able to have "unknown" as one of the options in the popup when selecting the category of morphology for biondi bodies. It would help with imaging Biondi Bodies that don't fit into any category.

Also, it would be helpful to be able to create marks on the grid to keep track of things that look like biondi bodies but aren't, as well as Biondi Bodies that are cut off in the Z-Plane.

**Comment by whuang37** [comment]
added an unknown option

**Comment by whuang37** [comment]
ignored marker added
