### ISSUE TITLE
Make multiple inclusion speck and spear distinct categories

### ISSUE THREAD

**Issue by bajohnso-uci** [whuang37/biondi_body_client#30]
Sorry this is coming so late, but I think the two types of multiple inclusions probably have different causes and therefore should be separately counted. It will be easier to combine them later if that is not the case than it will be to separate them on the basis of what is written in the notes if the distinction turns out to  be important.

**Comment by whuang37** [comment]
this is being looked into currently but may take a little bit to get it looking correct. we can make it so the notes will be added in the multi inclusion name and count if that would help

**Comment by bajohnso-uci** [comment]
Yes, having the name and count reflect whether "spears" or "specks" are entered in the notes for multiple inclusions (only) would work, so long as typos don't interfere.

**Comment by whuang37** [comment]
added
